### ISSUE TITLE
[BUG] Pulp Worker Crashes

### ISSUE THREAD

**Issue by PotentialIngenuity** [pulp/pulp-oci-images#497]
**Version**
3.24.1

**Describe the bug**
I am using the individual container deployment. I have a workflow that: Create Repo -> Create Remote -> Sync Repo -> Publish -> Distribute. Every time the workflow gets to the publish and sometimes the distribution task it crashes the worker container. I can restart the worker container and the waiting task will resume. 

```
+ /usr/bin/wait_on_postgres.py
Waiting on postgresql to start...
Checking postgres host postgres
Checking postgres port 5432
Postgres started!
+ /usr/bin/wait_on_database_migrations.sh
Checking for database migrations
Database migrated!
++ python3 -c 'from packaging.version import parse; from pulpcore.app.apps import PulpAppConfig; print('\''yes'\'' if parse(PulpAppConfig.version) >= parse('\''3.13.0.dev0'\'') else '\''no'\'')'
+ NEW_TASKING_SYSTEM=yes
+ echo yes
yes
+ [[ yes == \n\o ]]
+ export DJANGO_SETTINGS_MODULE=pulpcore.app.settings
+ DJANGO_SETTINGS_MODULE=pulpcore.app.settings
+ export PULP_SETTINGS=/etc/pulp/settings.py
+ PULP_SETTINGS=/etc/pulp/settings.py
+ export PATH=/usr/local/bin:/usr/bin/
+ PATH=/usr/local/bin:/usr/bin/
+ exec pulpcore-worker
pulp [None]: pulpcore.tasking.entrypoint:INFO: Starting distributed type worker
pulp [47856e8ae560410bb9b5095bc3690762]: pulpcore.tasking.tasks:INFO: Starting task 2583efc0-a340-45ec-b8f7-55385d5fa897
pulp [47856e8ae560410bb9b5095bc3690762]: pulp_rpm.app.tasks.publishing:INFO: Publishing: repository=rhel8/8.4/x86_64/appstream/os, version=1
pulp [47856e8ae560410bb9b5095bc3690762]: pulp_rpm.app.tasks.publishing:INFO: Publication: 33783710-5a5c-4c97-8fbe-291efcda0ecc created
pulp [47856e8ae560410bb9b5095bc3690762]: pulpcore.tasking.tasks:INFO: Task completed 2583efc0-a340-45ec-b8f7-55385d5fa897
pulp [02a5f4f7238b4ae381bd86db1daa0c0b]: pulpcore.tasking.tasks:INFO: Starting task a1a68ed4-25f4-4ea8-b9b8-83f7284fcb94
pulp [02a5f4f7238b4ae381bd86db1daa0c0b]: pulpcore.tasking.tasks:INFO: Task completed a1a68ed4-25f4-4ea8-b9b8-83f7284fcb94
Traceback (most recent call last):
  File "/usr/local/bin/pulpcore-worker", line 8, in <module>
    sys.exit(worker())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pulpcore/tasking/entrypoint.py", line 28, in worker
    NewPulpWorker().run_forever()
  File "/usr/local/lib/python3.8/site-packages/pulpcore/tasking/pulpcore_worker.py", line 378, in run_forever
    self.supervise_task(task)
  File "/usr/local/lib/python3.8/site-packages/pulpcore/tasking/pulpcore_worker.py", line 306, in supervise_task
    with TemporaryDirectory(dir=".") as task_working_dir_rel_path:
  File "/usr/lib64/python3.8/tempfile.py", line 780, in __init__
    self.name = mkdtemp(suffix, prefix, dir)
  File "/usr/lib64/python3.8/tempfile.py", line 358, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: './tmpo4hh2216'
```

**To Reproduce**
I used the [docker-compose](https://github.com/pulp/pulp-oci-images/blob/latest/images/compose/docker-compose.folders.yml) provided in this repo to deploy pulp and its containers. I am also using pulp squeeze for the workflow above. 

**Expected behavior**
Publish repos without crashing.

**Additional context**
I also noticed the worker count reported by the status API does not reflect the number of replicas.

```
deploy:
        replicas: 2
```
```
7c59bf391039   pulp/pulp-minimal:3.24.1   "/pulp-common-entryp…"   17 hours ago   Up About a minute                                                               docker-pulp_worker-1
7a8cedb97dbe   pulp/pulp-minimal:3.24.1   "/pulp-common-entryp…"   17 hours ago   Up 25 minutes                                                                   docker-pulp_worker-2
```
```
"online_workers": [
        {
            "pulp_href": "/pulp/api/v3/workers/66dcd50b-156a-4c4a-afc4-975b094b0ea2/",
            "pulp_created": "2023-06-06T05:13:08.181456Z",
            "name": "1@pulp-worker",
            "last_heartbeat": "2023-06-06T22:02:03.377925Z",
            "current_task": null
        }
    ],
```

**Comment by dkliban** [comment]
The compose file must have a 'hostname' defined for pulp-worker services. As a result all the workers are named the same thing. Pulp's tasking system fails to when this happens. The pulp-worker service should not have a hostname defined.
